name: release

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - docs/**
      - .env.example

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: go
          target-branch: main
